name: aed_map
description: App showing available AEDs

publish_to: "none"

version: 1.0.47+47

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  vector_map_tiles: ^7.3.1
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  flutter_map_location_marker: ^8.1.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  maps_launcher: ^2.0.1
  url_launcher: ^6.3.0
  flutter_map_dragmarker: ^6.0.0
  cross_fade: ^0.4.0
  connectivity_plus: ^6.0.5
  flutter_launcher_icons: ^0.14.1
  flutter_map_supercluster: ^5.0.0-dev.1
  flutter_map_marker_cluster: ^1.0.1
  shared_preferences: ^2.0.17
  cached_network_image: ^3.3.1
  hue_rotation: ^1.3.7
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_web_auth: ^0.6.0
  xml: ^6.2.2
  settings_ui: ^2.0.2
  feedback: ^3.1.0
  dotted_border: ^2.0.0+3
  image_picker: ^1.1.2
  image: ^4.0.17
  dio: ^5.1.2
  google_polyline_algorithm: ^3.1.0
  plausible_analytics: ^0.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_test: ^9.1.3
  package_info_plus: ^8.0.3
  sentry_flutter: ^8.9.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  mixpanel_flutter: ^2.2.0
  introduction_screen: ^3.1.14
  flutter_phoenix: ^1.1.1
  path_provider: ^2.1.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  win32: ^5.5.4
  geolocator_android: ^4.6.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_background: "#029140"
  adaptive_icon_foreground: "assets/icon.jpg"
  adaptive_icon_foreground_inset: 24

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/ml_models/
    - assets/onboarding/
